import type { Metadata } from "next";
import "./globals.css";
// import { geistSans, geistMono, poppins } from "./fonts";
import {Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased font-sans` }
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
